path <- "C:/Users/richa/Documents/Richard/Cours/ENSAE/2A/S2/Séries Temporelles/Time-Series-Forecasting-"
setwd(path)

# Importations ####

install.packages('zoo')
install.packages("fUnitRoots")
install.packages("urca")
install.packages("stats")

require(zoo)
library(fUnitRoots)
require(fUnitRoots) 
library(urca)

data <- read.csv(file.path("engrais.csv"), sep=";")[-c(1:3),]
colnames(data)<- c("dates","indices", "Codes")

# Stationnarisation ####
dates_char <- as.character(data$dates)
dates <- as.yearmon(seq(from=1990, to=2023+1/12, by=1/12)) #
indices <- as.numeric(as.character(data$indices))
engrais <- zoo(indices, order.by=dates)

summary(lm(engrais ~ dates))

dengrais=diff(engrais)

plot(engrais,ylim=c(0,300))
plot(dengrais,ylim=c(-80,80))

# Vérification de la stationnarisation ####
adf <- adfTest(engrais, lag=0, type="ct")
adf

Qtests <- function(series, k, fitdf=0) {
pvals <- apply(matrix(1:k), 1, FUN=function(l) {
pval <- if (l<=fitdf) NA else Box.test(series, lag=l, type="Ljung-Box", fitdf=fitdf)$p.value
return(c("lag"=l,"pval"=pval))
})
return(t(pvals))
}

adfTest_valid <- function(series,kmax,type){
k <- 0
noautocorr <- 0
while (noautocorr==0){
cat(paste0("ADF with ",k, " lags: residuals OK? "))
adf <- adfTest(series,lags=k,type=type)
pvals <- Qtests(adf@test$lm$residuals,24,fitdf=length(adf@test$lm$coefficients))[,2]
if (sum(pvals<0.05,na.rm=T) == 0) {
noautocorr <- 1; cat("OK \n")}
else cat("nope \n")
k <- k + 1
}
return(adf)
}


adf <- adfTest_valid(engrais,24,"ct")
adf <- adfTest(engrais, lag=6, type="ct")
adf


adf <- adfTest_valid(dengrais,24,"nc")
adf <- adfTest(dengrais, lag=5, type="nc")
adf


# Courbes temporelles des deux séries ####
plot(engrais,ylim=c(0,170))
plot(dengrais,ylim=c(-60,40))


# Détermination du modèle ARMA ####
par(mfrow=c(1,2))
#pacf(dengrais, 20)
acf(dengrais, 20)

pmax=6; qmax=3

x <- dengrais

mat <- matrix(NA, nrow = pmax + 1, ncol = qmax + 1)
rownames(mat) <- paste0("p=", 0:pmax)
colnames(mat) <- paste0("q=", 0:qmax)
AICs <- mat
BICs <- mat
pqs <- expand.grid(0:pmax, 0:qmax)
for (row in 1:dim(pqs)[1]) {
  p <- pqs[row, 1] 
  q <- pqs[row, 2] 
  estim <- try(arima(x, c(p, 0, q), include.mean = F))
  AICs[p + 1, q + 1] <- if (class(estim) == "try-error") NA else estim$aic
  BICs[p + 1, q + 1] <- if (class(estim) == "try-error") NA else BIC(estim)
}

AICs
AICs==min(AICs)
arima213 <- arima(engrais,c(2,1,3),include.mean=F)

BICs
BICs==min(BICs)
arima111 <- arima(engrais,c(1,1,1),include.mean=F)

adj_r2 <- function(model){
ss_res <- sum(model$residuals^2) #somme des residus au carre
p <- model$arma[1] #recupere l’ordre AR
q <- model$arma[2] #recupere l’ordre MA
ss_tot <- sum(dauto[-c(1:max(p,q))]^2) #somme des observations de l’echantillon au carre
n <- model$nobs-max(p,q) #taille de l’echantillon
adj_r2 <- 1-(ss_res/(n-p-q-1))/(ss_tot/(n-1)) #r2 ajuste
return(adj_r2)
}

adj_r2(arima213)
adj_r2(arima111)

# Q5 ARIMA ###
